---
apiVersion: batch/v1
kind: Job
metadata:
  # generateName: migration-job
  name: migration-job-4
  namespace: sre-13335-test
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    version: "3"
    # argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          /scripts/migration.sh
#          trap "touch /lifecycle/main-terminated" EXIT
        volumeMounts:
          - name: lifecycle
            mountPath: /lifecycle
          - name: scripts
            mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: lifecycle
        emptyDir: {}
      - name: scripts
        configMap:
          name: migration
          defaultMode: 0555
        
  backoffLimit: 0
