---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: migration-job
  # name: migration-job-4
  namespace: sre-13335-test
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 30']
      restartPolicy: Never
  backoffLimit: 0
