---
apiVersion: batch/v1
kind: Job
metadata:
  # generateName: migration-job
  name: migration-job-4
  namespace: sre-13335-test
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 60']
      restartPolicy: Never
  backoffLimit: 0
