---
apiVersion: batch/v1
kind: Job
metadata:
  # generateName: migration-job
  name: migration-job-1
  namespace: sre-13335-test
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    version: "1"
    # argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      shareProcessNamespace: true
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          /scripts/migration.sh
#          trap "echo $? > /lifecycle/main-terminated; exit $(cat /lifecycle/main-terminated);" EXIT
        volumeMounts:
          - name: lifecycle
            mountPath: /lifecycle
          - name: scripts
            mountPath: /scripts
      - name: busybox2
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          sleep 0.5
          echo 'starging second container'
          while true; do
            [[ -z "$(ps -ax | grep /scripts/migration.sh)" ]] && exit;
            echo 'migration still running...'
            sleep 1
          done;  
        volumeMounts:
          - name: lifecycle
            mountPath: /lifecycle
          - name: scripts
            mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: lifecycle
        emptyDir: {}
      - name: scripts
        configMap:
          name: migration
          defaultMode: 0555
        
  backoffLimit: 0
