---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migration
  namespace: sre-13335-test
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    version: "with-error"

data:
  migration.sh: |-
    echo "starting script"

    sleep 3

    echo "doing some stuff"

    sleep 180
    exit 123

    echo "last line"
    
